
package net.cateam.service.verify;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ImplVerify", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ImplVerify {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verify", targetNamespace = "http://webservice/", className = "net.cateam.service.verify.Verify")
    @ResponseWrapper(localName = "verifyResponse", targetNamespace = "http://webservice/", className = "net.cateam.service.verify.VerifyResponse")
    @Action(input = "http://webservice/ImplVerify/verifyRequest", output = "http://webservice/ImplVerify/verifyResponse")
    public boolean verify(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

}
